modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/gisellevonbingen/Minecraft-GravitationalModulatingAdditionalUnit/issues"

[[mods]]
    modId="gravitationalmodulatingunittweaks"
    version="${file.jarVersion}"
    displayName="Gravitational Modulating Additional Unit"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/gravitational-modulating-additional-unit"
    authors="gisellevonbingen"
    description=''''''
    itemIcon="gravitationalmodulatingunittweaks:module_gravitational_modulating_additional_unit" #for Catalogue

[[dependencies.gravitationalmodulatingunittweaks]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.22,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gravitationalmodulatingunittweaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gravitationalmodulatingunittweaks]]
    modId="mekanism"
    mandatory=true
    versionRange="[10.1.2,)"
    ordering="AFTER"
    side="BOTH"
