modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/gisellevonbingen/Minecraft-BossTools-Addon/issues"

[[mods]]
    modId="gravitationalmodulatingunittweaks"
    version="${file.jarVersion}"
    displayName="Gravitational Modulating Additional Unit"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/space-bosstools-giselle-addon"
    authors="gisellevonbingen"
    description=''''''
    itemIcon="gravitationalmodulatingunittweaks:module_gravitational_modulating_additional_unit" #for Catalogue

[[dependencies.gravitationalmodulatingunittweaks]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gravitationalmodulatingunittweaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gravitationalmodulatingunittweaks]]
    modId="mekanism"
    mandatory=true
    versionRange="[10.2.5,)"
    ordering="AFTER"
    side="BOTH"
